# -*- coding: utf-8 -*-
"""SSB_CS_DayTwo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KiyNVKXnOif0tZLjW8pWVL2pDuFopR6Y

# **Summer Springboard Computer Science Day Two**

## **Make a copy in your Google Drive**
## **Rename it to "Day2_FirstnameLastname"**
## **Share your notebook with your instructor using the top right share button**

### Creating and using Variables

Use the **type()** function below to determine the types of the variables
"""

var_one = 54
var_two = 23.2
var_three = True

# Your code here
# For example, running type(var_x) will tell you the type of var_x

"""First, assign your age to a variable called **age** and print it using the **print()** function from the last lesson.


"""

# Your code here

"""Now, create two string variables.  One should be called **first_name** and the second should be called **last_name** and they should contain what their name suggests."""

# Your code here

"""Next, convert the string **"123"** to an integer and print the result."""

# Your code here

"""Let's test out what happens when we mix different data types.

First, add an integer and a float together and print the result.
"""

# Your code here

"""Secondly, try to concatenate a string an an integer."""

# Your code here (you should expect an error when you run the code)

"""### \*\*\**PAUSE****

Edit the code below so that should_go_to_school contains the value **True**

Just replace the parts between the two **#** symbols; e.g.do not change **is_holiday** in the third line
"""

is_weekday = # Fill in the blank #
is_holiday = False
should_go_to_school = is_weekday # Fill in the blank # is_holiday

print("Should go to school: ", should_go_to_school)

"""Edit the code below so that can_go_hiking results in **False**, using the same rules as above."""

is_sunny = # Fill in the blank #
is_weekend = # Fill in the blank #
can_go_hiking = is_sunny or is_weekend

print("Can go hiking: ", can_go_hiking)

"""Using the same rules as above, edit the code below so that should_go_shopping results in **True**"""

is_fridge_empty = False
out_of_milk = # Fill in the blank #
out_of_bread = False
should_go_shopping = is_fridge_empty or out_of_milk # Fill in the blank # out_of_bread

print("Should go shopping: ", should_go_shopping)

"""### \*\*\**PAUSE****

Conditional Practice 1:

Write a program that takes a score (out of 100) and prints the grade.  The grading system is as follows:
   - Above 90: "Excellent"
   - 80 to 90: "Good"
   - 70 to 79: "Average"
   - Below 70: "Needs Improvement"
"""

score = 85 # You can change this value for different outputs

# Your code here

"""Conditional Practice 2:

Create a program that checks the time and prints a message if it's past 9PM but before 7AM.
   - If it's between 9 PM and 7 AM: Print "It's bedtime."
   - Otherwise: Print "It's not bedtime yet."
  
Hint: remember the logical operators we covered (**and**, **or**, **not**).
"""

time = 22  # Use 24-hour format, you can change this value for different outputs

# Your code here

"""Conditional Practice 3:

There are 3 things wrong with the code below!  Fix it so that it follows these specifications:

A movie theater charges different ticket prices based on age. Write a program that applies the following rules:

  -  Below age 13: $8

  -  Age 13 to 59: $12

  -  Age 60 and above: $10

Hint: remember what we learned about the **if** statement syntax (order of statements, indentation) and also pay special attention to the age ranges specified.
"""

age = 45  # You can change this value for different outputs

if age <= 13:
    print("Ticket Price: $8")
else:
print("Ticket Price: $10")
elif age <= 59:
    print("Ticket Price: $12")