# -*- coding: utf-8 -*-
"""SSB_CS_DayFive.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/118zLeLaQjaHs8onYmrVeiInIBiVH6Pvo

# **Summer Springboard Computer Science Day Five**

## **Make a copy in your Google Drive**
## **Rename it to "Day5_FirstnameLastname"**
## **Share your notebook with your instructor using the top right share button**

### Try / Except Blocks

Problem 1: Handling Invalid Input

Modify the code below so that we have a program that asks the user to input an integer and prints the square of the number.  We want to use **try** / **except** blocks to handle non-integer inputs.  When the input is not an integer, you should have the program print "Error: Please enter a valid integer."

Hint: You will want to make use of the **ValueError** exception

Challenge: Find a way to have the program continue asking for an integer if the user does not enter one.
"""

def square_number():
    num = int(input("Enter an integer: "))
    print("Square of the number:", num ** 2)

square_number()

"""Problem 2: Fixing **safe_divide()**

The code below has some problems with it!  Use your debugging skills to fix it so that it works properly.

Hint: Remember the **ZeroDivisionError** exception from the slides.
"""

def safe_divide():
    try:
        num1 = float(input("Enter the first number: "))
        num_2 = float(input("Enter the second number: "))
        result = num1 / num2
    else:
        print("Result:", result)
    except:
        print("Error: Cannot divide by zero.")

safe_divide()

"""Problem 3: Code Analysis and Fix-Up

Read the code below to try to determine what it is trying to do.  The issue with this code is that the variable names are not expressive, which makes it harder for others to tell what is going on with it.  

Your job is to write in the comment at the end what you believe the code is doing.  Then, you should fix the variable and function names so that they are more expressive and detailed.
"""

def f():
    try:
        a = int(input("Enter your age: "))
        b = int(input("Enter your year of birth: "))
        c = 2050 - b
        print("You will be", c, "years old in 2050.")
    except ValueError:
        print("Error: Please enter valid numbers.")
    except TypeError:
        print("Error: An error occurred with the types of inputs.")

f()

# Your description here

"""### \*\*\**PAUSE****

### Libraries

Problem 1: Fix the Code

The code below is relying on the libraries **matplotlib** (specifically the **pyplot** module) and **numpy**.  The function **line_plot()** is written correctly, but when it is called it doesn't work.  What are we missing?  What do we need to add?
"""

def line_plot():
    x = np.arange(0, 10, 0.1)
    y = np.sin(x)

    plt.plot(x, y)
    plt.title('Sinusoidal Curve')
    plt.xlabel('X-axis')
    plt.ylabel('Y-axis')
    plt.show()

line_plot()

"""Problem 2: Dice Simulator

Using the **random** library, write a program that simulates the roll of an **n**-sided die.  Then, print the outcome of the simulated roll.

When calling the function, **simulate_dice_roll()**, the user should be able to input the number of sides that they want as an argument.

Challenge: write code to handle errors if the user enters a non-integer.
"""

# Your code here

simulate_dice_roll(6)  # simulates dice roll for a 6-sided die.

"""Problem 3: Response Time

Using the **time** library, create a function **measure_response_time()** that measures the time it takes the user to press the **Enter** key after a prompt.

Steps:
1.   import the library
2.   Ask the user to press **Enter** once the prompt appears.
3.   Save the start time
4.   Prompt the user to press **Enter** again
5.   Save the end time
6.   Calculate the response time and print it

Hint: to get the time with **time**, you can use **time.time()**.
"""

# Your code here

measure_response_time()