# -*- coding: utf-8 -*-
"""SSB_CS_DayThree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lTj865byEJWZTLUm2ZtiYF2omWlIqlFY

# **Summer Springboard Computer Science Day Two**

## **Make a copy in your Google Drive**
## **Rename it to "Day2_FirstnameLastname"**
## **Share your notebook with your instructor using the top right share button**

### Creating and Using Lists

Problem 1: Add and Remove Elements from a List

Complete the following list of steps so that when the cell is run, **['red', 'blue', 'yellow']** is printed.

1.  Create a list named **colors** with the elements **"red"**, **"green"**, **"blue"**.

2.   Add **"yellow"** to the end of the list

3.   Remove **"green"** from the list
"""

# Your code here

print(colors)

"""Problem 2: List Concatenation

Strings are like lists of characters.  Remember that we used the concatenation operator, **+**, to combine two strings.  We can use the same operator to concatenate (combine) two lists.

Given the two lists below, **list_1** and **list_2**, concatenate them into a new list called **combined_list** and print it.
"""

list_1 = [1, 2, 3]
list_2 = [4, 5, 6]

# Your code here

"""Problem 3: Tuple Creation and Access

Create a tuple **weekdays** containing the days of the week.  Then, print the element at index 3 in **weekdays**.
"""

# Your code here

"""Problem 4: Dictionary Manipulation

Complete the following list of steps:

1.   Create a dictionary **person** with keys **name** and **age** and values **Alice** and **30** respectively.

2.   Add a new key-value pair **"city" : "New York"**

3.   Update the **age** to **31**

4.   Print the **person** dictionary.
"""

# Your code here

"""Problem 5: Printing Elements of a List

Complete the code below so that each element of **treasure_chest** is printed.

This task may feel a bit repetitive.  If only there were a quicker way of doing this...
"""

treasure_chest = ["gems", "gold", "bones", "diamonds", "rings"]

print(treasure_chest[0])
print(treasure_chest[1])
# Your code here

"""### \*\*\**PAUSE****

Problem 1: List Iteration

1.   Create a list of your three favorite fruits / vegetables called **favorite_healthy_foods**

2.   Use a **for** loop to iterate over the list and print each fruit in uppercase*

\* to make a string upppercase, use the **upper()** function.  For example, **my_string.upper()** makes **my_string** uppercase.
"""

# Your code here

"""Problem 2: Conditional within a Loop

Given a list of numbers, **numbers**, use a **for** loop to iterate through the list and print each number that is greater than 10.
"""

numbers = [4, 15, 9, 20, 3]  # you can edit this list to try out different sets of numbers

# Your code here

"""Problem 3: Summation within a Loop

Given a list of integers, **integers**, use a **for** loop to calculate the sum of all integers in the list.  Then, print the total sum.
"""

integers = [5, 10, 15, 20]  # you can edit this list to try out different sets of integers

# Your code here

"""Problem 4: While Loop With Condition

1.   Initialize a variable **counter** to 0.

2.   Use a **while** loop to increment **counter** by 1 as long as **counter** is less than 5.

3.   Print the value of **counter** in each iteration.
"""

# Your code here