# -*- coding: utf-8 -*-
"""SSB_CS_DaySix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TLOQgNo9FBB6eSIL9AJMVMz5ISRXXrzJ

# **Summer Springboard Computer Science Day Six**

## **Make a copy in your Google Drive**
## **Rename it to "Day6_FirstnameLastname"**
## **Share your notebook with your instructor using the top right share button**

### Numpy

Problem 1: Array Transformation

Create a **NumPy** array of the first 10 even numbers and reshape it into a 2x5 matrix.

Hint: Look up the **np.arrange()** documentation if needed.
"""

import numpy as np

# Your code here

"""Problem 2: Array Operations

Given an array of temperatures in Celsius, convert these to Fahrenheit

Hint: To convert from Celsius to Fahrenheit, we use the function **f(C) = C * (9/5) + 32**
"""

import numpy as np

temperatures_celsius = np.array([20, 22, 19, 24, 25, 26])
# Your code here
print(temperatures_fahrenheit)

"""Problem 3: Conditional Selection

Create a **NumPy** array of integers from 1 to 15 and select values greater than 10
"""

import numpy as np

# Your code here

"""### \*\*\**PAUSE****

### Pandas

Problem 1: DataFrame Creation and Selection

Create a **Pandas** DataFrame using the below **fruits_data** dictionary.  Then, select the rows where **Quantity** is greater than 5
"""

import pandas as pd

fruits_data = {
    'Name': ['Apple', 'Banana', 'Cherry', 'Date'],
    'Quantity': [5, 8, 3, 12],
    'Price per Unit': [0.5, 0.2, 0.75, 1]
}

# Your code here

"""Problem 2: Code Analysis

Read through the below code snippet.  Then, write a comment for each block of code explaining what is going on.  After this, answer the following comprehension questions:
1.  What does axis=1 signify in the calculation of the average scores?
2.  If a new subject were added to the dataset, how would you modify the code to include it in the average score calculation?
3.  What insights can be drawn about the performance of the class in each subject based on the average scored calculated?
"""

import pandas as pd
import numpy as np

# Sample data: Student names, and their scores in Mathematics, English, and Science
data = {
    'Student': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Mathematics': [82, 91, 78, 85, 92],
    'English': [88, 79, 85, 83, 94],
    'Science': [94, 88, 78, 92, 89]
}

# Insert comment here
students_df = pd.DataFrame(data)

# Insert comment here
students_df['Average'] = np.mean(students_df[['Mathematics', 'English', 'Science']], axis=1)

# Insert comment here
students_df['Passed'] = students_df['Average'] >= 85

print(students_df)

# Insert comment here
highest_average = students_df['Average'].max()

# Insert comment here
top_students = students_df[students_df['Average'] == highest_average]['Student'].tolist()

# Insert comment here
average_math = students_df['Mathematics'].mean()
average_english = students_df['English'].mean()
average_science = students_df['Science'].mean()

print(f"\nHighest Average Score: {highest_average}")
print(f"Top Students: {top_students}")
print(f"\nAverage Scores:\nMathematics: {average_math}\nEnglish: {average_english}\nScience: {average_science}")

# Insert comment here
pass_rate = (students_df['Passed'].sum() / len(students_df)) * 100
print(f"\nPass Rate: {pass_rate}%")