# -*- coding: utf-8 -*-
"""SSB_CS_DayFour.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ye3supGalVDVGnvQ-VfduK8_vmTIwu9w

# **Summer Springboard Computer Science Day Four**

## **Make a copy in your Google Drive**
## **Rename it to "Day4_FirstnameLastname"**
## **Share your notebook with your instructor using the top right share button**

### Fun with Functions

Problem 1: Fill in the Blanks

Fill in the blanks below between the **#** symbols so that you have a working function that converts Fahrenheit to Celsius.
"""

# Fill in the blank # convert_to_celsius(# Fill in the blank #):
    # Fill in the blank # (fahrenheit - 32) * 5 / 9

celsius = convert_to_celsius(68)  # Example usage
print("Temperature in Celsius:", celsius)

"""Problem 2: Area Calculation Function

Create a function called **triangle_area** that takes the base and height of a triangle and returns its area.

Hint: The formula for the area of a triangle is 0.5 * base * height
"""

# Your code here

area = triangle_area(10, 5)  # Example usage
print("Area of triangle:", area)

"""Problem 3: Number of Digits

Write a function called **count_digits** that takes an integer and returns the number of digits in it.

Hint: There is a function, **len()**, that takes a string as an input and gives the length of the string as an output.  You may also want to make use of type casting.
"""

# Your code here

print(count_digits(12345))  # Should print 5

"""Problem 4: Sum of a List

Write a function called **sum_list** that takes a list of numbers as an argument and returns the sum of all the numbers in the list.

Hint: We did the code for summing a list yesterday.
"""

# Your code here

print(sum_list([1, 2, 3, 4, 5]))  # Should print 15

"""Problem 5: Odd or Even

Write a function called **is_odd** that takes a number as an argument and returns **True** if the number is odd and **False** if it is even.

Hint: There is a binary operator, **%**, which is called modulo. **a % b** returns the remainder of **a / b**.  So, for example, **8 % 3 = 2**, since the remainder of **8 / 3** is **2**. What number divides every even number? What is the remainder of this division?
"""

# Your code here

print(is_odd(7))  # Should print True
print(is_odd(4))  # Should print False

"""### \*\*\**PAUSE****

### Debugging
Problem 1: Error Messages

Each of the 3 below code blocks has some error in the code.  Run the code block to see the error message.  In the commented space in each block, write the type of error (this will either be name, type, or syntax) and why you believe this error is occurring.  Then, take a few minutes to fix the bug so that the code works as it should.
"""

def print_message(message)
    print("Message:", message)

print_message("Hello, Python!")

# Your comment here

age = input("Enter your age: ")
print("In 10 years, you will be " + age + 10 + " years old.")

# Your comment here

def calculate_area(radius):
    area = 3.14 * radiius**2
    return area

print(calculate_area(5))

# Your comment here

"""Problem 2: Using Print Statements

Debug the following 2 code blocks, using print statements to figure out where the bugs are.

Note: Here is the documentation for the **range()** function in case you are unfamiliar with it: https://docs.python.org/3/library/stdtypes.html#range

"""

# The following loop is supposed to print numbers from 1 to 5, but it's not
# working as expected.
for i in range(5):
    print(i)

# The function add_numbers is not returning the expected result
def add_numbers(a, b):
    result = a + b
    return result

print(add_numbers(2, "3"))

"""Problem 3: Breaking Down the Code

Debug the following 2 code blocks by breaking down the code into smaller segments to identify and fix issues.
"""

# The function calculate_discount is supposed to return the discounted price of
# an item after applying a discount percentage, but it's returning incorrect
# results. Break down the function and test its components to find and fix the
# error.
def calculate_discount(price, discount):
    discount_amount = price * (discount / 100)
    new_price = price - discount
    return new_price

print(calculate_discount(100, 20))  # Expected output: 80

# A loop is intended to sum all even numbers in a list, but it’s giving the
# wrong total. Break the loop into smaller parts to find and correct the
# mistake.
numbers = [1, 2, 3, 4, 5, 6]
total = 0
for number in numbers:
    if number % 2 == 1:
        total += number
print(total)  # Expected output: 12 (sum of 2, 4, 6)

"""Problem 4: **pdb**

For this problem, we will use **pdb**, Python's built-in debugger.  To use **pdb**, run each of the 2 code blocks below and use the following directions:

1.    Use **n** to step through each line in the function.
2.    Use **p combined_sum** to inspect the combined_sum list after each addition.
3.    Check if elements from both lists are being added correctly.
"""

# You have a function that is supposed to calculate the factorial of a number,
# but it's returning incorrect results. Use pdb to step through the code and
# find the issue.

import pdb

def factorial(n):
    pdb.set_trace()
    result = 1
    for i in range(n):
        result *= i
    return result

print(factorial(5))  # Expected output: 120

# A program is designed to sum the elements of two lists and store the results
# in a new list. However, the output is not as expected.
# Use pdb to inspect the variables.

import pdb

def sum_lists(list1, list2):
   # pdb.set_trace()
    combined_sum = []
    for i in range(len(list1)):
        combined_sum.append(list1[i] - list2[i])
    return combined_sum

result = sum_lists([1, 2, 3], [4, 5, 6])
print(result)  # Expected output: [5, 7, 9]